# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# These commented ones are kubernetes 1.11 and client 8.0.0, but we can't use them with EKS yet.
# [[constraint]]
#   name = "k8s.io/api"
#   version = "kubernetes-1.11.2"
#
# [[constraint]]
#   name = "k8s.io/apimachinery"
#   version = "kubernetes-1.11.2"
#
# [[constraint]]
#   name = "k8s.io/client-go"
#   version = "8.0.0"


[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.7"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.7"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

