apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:sts::657070751326:assumed-role/EKSRole/EKS-Create-ConfigMap
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters
metadata:
  name: aws-auth
  namespace: kube-system
kind: ConfigMap
